name: Docker Image CI

on:
  push:
    paths-ignore: [ 'README.md']
  pull_request:
    branches: [ main ]
    paths-ignore: [ 'README.md']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --target test --tag my-test-image .
    - run: docker run --env-file .env.test my-test-image tests   
    - run: docker run -e TRELLO_KEY=${{ secrets.TRELLO_KEY }} -e TOKEN=${{ secrets.TOKEN }} my-test-image tests_e2e







